@startuml

left to right direction

actor Player1
actor Player2
actor Server
actor GUI

Player1 --> (Seleziona Colonna)
Player1 --> (Visualizza Vittoria)

Player2 --> (Seleziona Colonna)
Player2 --> (Visualizza Vittoria)

(GUI --> (Visualizza Griglia))
(GUI --> (Visualizza Vittoria))

Player1 --> (Invia Mossa)
Player2 --> (Invia Mossa)

(Invia Mossa) --> (Elabora Mossa)
(Elabora Mossa) --> (Aggiorna Griglia)
(Aggiorna Griglia) --> (Comunica Vittoria)

@enduml
