@startuml
left to right direction

actor "Player 1" as P1
actor "Player 2" as P2
actor GUI as G

rectangle Client {
    usecase "Seleziona Colonna" as C_UC1 #YellowGreen
    usecase "Visualizza Vittoria" as C_UC2 #YellowGreen
}

P1 --> C_UC1
P1 --> C_UC2

P2 --> C_UC1
P2 --> C_UC2

G --> C_UC1
G --> C_UC2

rectangle TCPClient {
    usecase "Invia Mossa/Elabora Mossa" as S_UC1 #GreenYellow
    usecase "Aggiorna Griglia" as S_UC2 #GreenYellow
    usecase "Comunica Vittoria" as S_UC3 #GreenYellow
}

C_UC1 <--> S_UC1
C_UC2 <--> S_UC2
C_UC2 <--> S_UC3

@enduml
